# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.arm-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

## Re-enable when Tier 2 support is added for proc-macro crates

# [target.x86_64-unknown-linux-musl]
# rustflags = [
#   "-C", "target-feature=+crt-static",
#   "-C", "link-self-contained=yes",
# ]

# [target.arm-unknown-linux-musl]
# rustflags = [
#   "-C", "target-feature=+crt-static",
#   "-C", "link-self-contained=yes",
# ]
