[package]
name = "scenario"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
log = { workspace = true }
env_logger = "0.11"
toml = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
