name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run clippy and tests
        run: |
          cargo clippy -p sinkd
          cargo test -p sinkd

  build:
    needs: lint
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-amd64
            arch: amd64
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform: linux-arm64
            arch: arm64
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows-amd64
          - runner: windows-latest
            target: arm-pc-windows-msvc
            platform: windows-arm64
          - runner: macos-latest
            target: x86_64-apple-darwin
            platform: darwin-amd64
            arch: amd64
          - runner: macos-latest
            target: aarch64-apple-darwin
            platform: darwin-arm64
            arch: arm64


    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build
        run: |
          mkdir -p artifacts
          VERSION=$(cargo pkgid -p sinkd | cut -d# -f2)
          echo "version=${VERSION}" >> $GITHUB_ENV
          cargo build --release -p sinkd --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/sinkd artifacts/sinkd-${{ matrix.platform }}-${VERSION}
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: sinkd-artifacts
          path: artifacts/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: sinkd-artifacts
          merge-multiple: true
          path: artifacts/
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.version }}
          body: |
            sinkd ${{ env.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/
      



